### PR TITLE
Clearer renames and consistent property descriptions

### PR DESCRIPTION
**Pull request by wnbaum**
Renamed properties mostly according to what Justin suggested. Also moved all texture assets into a subdirectory of `assets` to make it more clear where to find them and added a "mod" to the doc describing this. Not sure if there is a better way of doing this where all of the scene files don't get modified, as Godot automatically updates the resource paths.

Also, I noticed that the property descriptions were not always showing up for whatever reason. I found that adding a `class_name` to many of the scripts made the descriptions appear even when I reloaded the project and even generated a documentation page. I am on Godot 4.2.2-stable - maybe you can try to replicate the bug on your end without the `class_name` because I don't think it should be necessary, but it does seem like good practice anyways. Thanks!

https://phabricator.endlessm.com/T35416

### CODE REVIEW

**Review by dylanmccall — COMMENTED** [review]
This looks like a good set of changes to me. I didn't run into the same issue as you with the missing documentation / property descriptions - they all showed up just fine without additional poking - but I hadn't opened the project in the Godot editor recently until after I'd checked out your branch. I'm certainly curious how it goes for @manuq :)

I agree with using `class_name` consistently, in particular since it would allow us to use type hints and have the code be more self-documenting. There _is_ a footgun built in to Godot here where a beginner is led to think "oh, I can call `BananaBall.new()` and add it to my scene" but it turns out that doesn't work because that class doesn't know anything about its scene file; you _have to_ load and instantiate the scene itself, which results in a root node that is the `BananaBall` type and has all its properties and children from the scene. Alas, I don't know if there are any conventions to avoid mishaps there.

**Comment by wjt** [comment]
Needs updating now that #16 was merged.

**Review by manuq — CHANGES_REQUESTED** [review]
Thanks @wnbaum, two suggestions besides the request from @wjt about adjusting for the linter changes already merged:
- Make the commit message a bit more descriptive of what's being changed. Eg "Move all textures to a textures folder". I went through all the diff trying to find if that was the only rename or if there were more as proposed by Justin.
- Ideally do different changes in different commits. Please move the addition of class names to its own commit.

@dylanmccall thanks for pointing us to the proposals on class names. The only reason I didn't add class names yet was because of that. Adding a new node lets you add a ball, but that doesn't make sense without instantiating the whole scene and will probably confuse learners:
Captura desde 2024-05-23 10-20-29

But I think we should not constrain ourselves with this for now and start subclassing if we feel necessary.

**Comment by manuq** [comment]
@wnbaum oh and yes I confirm the bug about missing docs on mouse over. I fixed it by moving aside the `.godot` folder. I think it's worth reporting upstream in the Godot repo. I saved the previous `.godot` folder if it's useful for further debugging. It would be useful to check which change provoked the bug, if the renaming of assets or the addition of class names.
Captura desde 2024-05-23 10-01-16

**Comment by manuq** [comment]
@wnbaum sorry I see that you also renamed the variables for GameLogic. They were occluded by the texture change.

**Pull request merged**
